#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vsftpd[-1]
	add ucitrack vsftpd
	set ucitrack.@vsftpd[-1].init=vsftpd
	commit ucitrack
EOF

rm -f /tmp/luci-vsftpd
killall -HUP rpcd 2>/dev/null
exit 0
