#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vsftpd[-1]
	add ucitrack vsftpd
	service vsftpd enable
	set ucitrack.@vsftpd[-1].init=vsftpd
	commit ucitrack
EOF

rm -f /tmp/luci-vsftpd
exit 0
