include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=luci-app-koolproxyR
PKG_VERSION:=3.8.4
PKG_RELEASE:=5

PKG_MAINTAINER:=panda-mute <wxuzju@gmail.com>
PKG_LICENSE:=GPLv3
PKG_LICENSE_FILES:=LICENSE

PKG_BUILD_PARALLEL:=1

RSTRIP:=true

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesci-app-koolproxyR
	SECTION:=luci
	CATEGORY:=LuCI
	SUBMENU:=3. Applications
	TITLE:=LuCI support for koolproxyR
	DEPENDS:=+openssl-util +ipset +dnsmasq-full +@BUSYBOX_CONFIG_DIFF +iptables-mod-nat-extra +wget
	MAINTAINER:=panda-mute
endef

define Packa$(TOPDIR)/feeds/packagesci-app-koolprox$(TOPDIR)/feeds/packagesscription
	This package contains LuCI configuration pages for koolproxy.
endef

define Bui$(TOPDIR)/feeds/packagesmpile
endef

define Packa$(TOPDIR)/feeds/packagesci-app-koolprox$(TOPDIR)/feeds/packagesstinst
$(TOPDIR)/feeds/packagesn/sh
if [ -z "$${IPKG_INSTROOT}" ]; then
	( $(TOPDIR)/feeds/packagesc/uci-defaul$(TOPDIR)/feeds/packagesci-koolproxy ) && rm -$(TOPDIR)/feeds/packagesc/uci-defaul$(TOPDIR)/feeds/packagesci-koolproxy
	rm -$(TOPDIR)/feeds/packagesp/luci-indexcache
fi
exit 0
endef

define Packa$(TOPDIR)/feeds/packagesci-app-koolprox$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesc/uci-defaults
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesc/config
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesc/adblocklist
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesc/init.d
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesb/upgra$(TOPDIR)/feeds/packagesep.d
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages8n/
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesntroller
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesd$(TOPDIR)/feeds/packagesi/koolproxy
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesew
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesolproxy
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/sbin
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolproxy
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesta
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesles/

	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesc/uci-defaul$(TOPDIR)/feeds/packagesci-koolproxy $($(TOPDIR)/feeds/packagesc/uci-defaul$(TOPDIR)/feeds/packagesci-koolproxy
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesc/init$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesc/init.d/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesc/conf$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesc/config/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesc/adblockli$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesc/adblocklist/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesb/upgra$(TOPDIR)/feeds/packagesep$(TOPDIR)/feeds/packagesolproxy $($(TOPDIR)/feeds/packagesb/upgra$(TOPDIR)/feeds/packagesep.d/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesd$(TOPDIR)/feeds/packagesi/koolpro$(TOPDIR)/feeds/packagesobal.lua $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesd$(TOPDIR)/feeds/packagesi/koolpro$(TOPDIR)/feeds/packagesobal.lua
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesd$(TOPDIR)/feeds/packagesi/koolpro$(TOPDIR)/feeds/packagess_rule.lua $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesd$(TOPDIR)/feeds/packagesi/koolpro$(TOPDIR)/feeds/packagess_rule.lua
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesntroll$(TOPDIR)/feeds/packagesolproxy.lua $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packagesntroll$(TOPDIR)/feeds/packagesolproxy.lua
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesolproxy/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesolproxy.zh-cn.lmo $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesolproxy.zh-cn.lmo
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sb$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesr/sbin/
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesn_ca.sh $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesta/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesenssl.cnf $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesta/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packageser.txt $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesta/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesurce.list $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesta/
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesles/
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesmanagement $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesmanagement
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesupdate $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesupdate
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesolproxy_ipset.conf $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesolproxy_ipset.conf
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagessmasq.adblock $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagessmasq.adblock
ifeq ($(ARCH),mipsel)
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesn/mipsel $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesolproxy
endif
ifeq ($(ARCH),mips)
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesn/mips $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesolproxy
endif
ifeq ($(ARCH),i386)
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesn/i386 $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesolproxy
endif
ifeq ($(ARCH),x86_64)
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesn/x86_64 $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesolproxy
endif
ifeq ($(ARCH),arm)
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesn/arm $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesolpro$(TOPDIR)/feeds/packagesolproxy
endif
endef

$(eval $(call BuildPackage,luci-app-koolproxyR))
