# Copyright (C) 2019 CCnut
#
# This is free software, licensed under the GNU General Public License v2.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=Support for Netkeeper
LUCI_DEPENDS:=+netkeeper
LUCI_PKGARCH:=all
PKG_VERSION:=1.3
PKG_RELEASE:=3

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
