#
# Copyright (C) 2018 By-Ameng Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=luci-app-guest-wifi
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=2

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
