#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cifs[-1]
	add ucitrack cifs
	set ucitrack.@cifs[-1].init=cifs
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0