#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frps[-1]
	add ucitrack frps
	set ucitrack.@frps[-1].init=frps
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
killall -HUP rpcd 2>/dev/null
exit 0
