#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frps[-1]
	add ucitrack frps
	service frps enable
	set ucitrack.@frps[-1].init=frps
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
