# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI support disable usb3
LUCI_DEPENDS:= 
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-usb3disable
PKG_VERSION:=1.0
PKG_RELEASE:=1

define Packa$(TOPDIR)/feeds/packagesci-app-usb3disab$(TOPDIR)/feeds/packagesstall
    $(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/luci
	cp -pR$(TOPDIR)/feeds/packagesas$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/luci
	$(INSTALL_DIR) $(1)/
	cp -pR$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packages$(1)/
endef

define Packa$(TOPDIR)/feeds/packagesci-app-usb3disab$(TOPDIR)/feeds/packagesstinst
$(TOPDIR)/feeds/packagesn/sh
	rm -$(TOPDIR)/feeds/packagesp/luci-indexcache
	rm -$(TOPDIR)/feeds/packagesp/luci-modulecache/*
exit 0
endef
include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature

