# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI for sysupgrade
LUCI_DEPENDS:=+luci-base
PKG_MAINTAINER:=GaryPang <garyp@qq.com>

define Packa$(TOPDIR)/feeds/packagesci-theme-ed$(TOPDIR)/feeds/packagesstinst
  $(TOPDIR)/feeds/packagesn/sh
  rm -R$(TOPDIR)/feeds/packagesr/luci-*cache*
endef

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
