#!/bin/sh
[ "$1" = check ] || exit 1
LOCK=/var/lock/ssr-plus.lock
LOG=/tmp/ssrplus.log
D="date +'%Y-%m-%d %H:%M:%S'"
# 防止重复启动
[ -f $LOCK ] && exit 1
touch $LOCK
sleep 2
while ! curl -so /dev/null -m 3 www.baidu.com;do
	sleep 2
done
echo "`eval $D` SSR-rules : Check network status successful!" >> $LOG
rm -f $LOCK
if [ ! -s /tmp/ssrplus/china.txt ] || ([ "$(uci -q get shadowsocksr.@global[0].run_mode)" = gfw -o "$(uci -q get shadowsocksr.@global[0].gfw_mode)" = 1 ] && [ ! -s /tmp/ssrplus/gfw.list ]);then
	echo "`eval $D` SSR-rules : Download IP/GFW files..." >> $LOG
	/usr/share/ssrplus/update --First &
else
	/etc/init.d/shadowsocksr start &
fi
