#!/usr/bin/lua
local ucursor=require "luci.model.uci".cursor()
local json=require "luci.jsonc"
local server_section=arg[1]
local proto=arg[2]
local local_port=arg[3]
local ip_addr=arg[4]
local server=ucursor:get_all("shadowsocksr",server_section)

local trojan={
	log_level=3,
	run_type=proto,
	local_addr="0.0.0.0",
	local_port=tonumber(local_port),
	remote_addr=ip_addr,
	remote_port=tonumber(server.server_port),
	udp_timeout=60,
	password={server.password},
	ssl={
		verify=(server.insecure~="1") and true or false,
		verify_hostname=(server.insecure~="1") and true or false,
		cert=(server.certificate=="1") and server.certpath or "",
		cipher="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384",
		cipher_tls13="TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
		sni=(server.tls_host~=nil) and server.tls_host or server.server,
		alpn={"h2","http/1.1"},
		curves="",
		reuse_session=true,
		session_ticket=false,
		},
		tcp={
			no_delay=true,
			keep_alive=true,
			reuse_port=true,
			fast_open=(server.fast_open=="1") and true or false,
			fast_open_qlen=20
		}
}
print(json.stringify(trojan, 1))
