#!/bin/sh
NAME=shadowsocksr

uci_get_by_name(){
	ret=$(uci -q get $NAME.$1.$2)
	echo ${ret:=$3}
}

uci_get_by_type(){
	ret=$(uci -q get $NAME.@$1[0].$2)
	echo ${ret:=$3}
}

redir_tcp=$1
kcp=$2
redir_udp=$3
redir_nf=$4
smartdns=$5
chinadns=$6
socks5=$7
server_count=$8
trojan_udp=$9
ip_port=$10
trojan_udp_port=$11
server=`cat /tmp/etc/$NAME.include | grep '\-A SS_SPEC_WAN_AC \-d' | grep RETURN | awk '{print$4}' | sed 's/\/.*//'`
GLOBAL_SERVER=$(uci_get_by_type global global_server)
kcp_port=$(uci_get_by_name $GLOBAL_SERVER kcp_port)
server_port=$(uci_get_by_name $GLOBAL_SERVER server_port)
password=$(uci_get_by_name $GLOBAL_SERVER kcp_password)
kcp_param=$(uci_get_by_name $GLOBAL_SERVER kcp_param)
gfw_mode=$(uci_get_by_type global gfw_mode 0)
[ "$password" != "" ] && password="--key "${password}

while :;do
	sleep 30
#redir tcp
	if [ $redir_tcp -gt 0 ];then
		t=`ps -w | grep ssr-retcp | grep -v grep | wc -l`
		if [ $t -lt $redir_tcp ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") Redir TCP Error. Restart!" >> /tmp/ssrplus.log
			/etc/init.d/shadowsocksr restart
			exit 0
		fi
	fi
#kcptun
	if [ $kcp = 1 ];then
		t=`ps -w | grep kcptun-client | grep -v grep | wc -l`
		if [ $t = 0 ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") SSR KCPTUN Error. Restart!" >> /tmp/ssrplus.log
			killall -q -9 kcptun-client
			$(which kcptun-client) -r $server:$kcp_port -l :$server_port $password $kcp_param &
		fi
	fi
#redir udp
	if [ $redir_udp = 1 ];then
		t=`ps -w | grep ssr-reudp | grep -v grep | wc -l`
		if [ $t = 0 ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") Redir UDP Error. Restart!" >> /tmp/ssrplus.log
			/etc/init.d/shadowsocksr restart
			exit 0
		fi
	fi
#redir netflix
	if [ $redir_nf = 1 ];then
		t=`ps -w | grep ssr-nf | grep -v grep | wc -l`
		if [ $t = 0 ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") Redir Netflix Error. Restart!" >> /tmp/ssrplus.log
			/etc/init.d/shadowsocksr restart
			exit 0
		fi
	fi
#smartdns
	if [ $smartdns = 1 ];then
		t=`ps -w | grep smartdns | grep -v grep | wc -l`
		if [ $t = 0 ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") SmartDNS Error. Restart!" >> /tmp/ssrplus.log
			killall -q -9 smartdns
			$(which smartdns) -c /var/etc/smartdns/smartdns.conf
		fi
	fi
#chinadns-ng
	if [ $chinadns = 1 ];then
		t=`ps -w | grep chinadns-ng | grep -v grep | wc -l`
		if [ $t = 0 ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") ChinaDNS-NG Error. Restart!" >> /tmp/ssrplus.log
			$(which chinadns-ng) -l 5337 -c '127.0.0.1#5336' -t '127.0.0.1#5335' -4 china_v4 -6 china_v6 -f -n $([ $gfw_mode = 1 ] && echo -g /tmp/ssrplus/gfw.list) >/dev/null 2>&1 &
		fi
	fi
#localsocks
	if [ $socks5 = 1 ];then
		t=`ps -w | grep ssr-socks | grep -v grep | wc -l`
		if [ $t = 0 ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") Global Socks Server Error. Restart!" >> /tmp/ssrplus.log
			/etc/init.d/shadowsocksr restart
			exit 0
		fi
	fi
#server
	if [ $server_count -gt 0 ];then
		t=`ps -w | grep ssr-server | grep -v grep | wc -l`
		if [ $t -lt $server_count ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") SSR Server Error. Restart!" >> /tmp/ssrplus.log
			/etc/init.d/shadowsocksr restart
			exit 0
		fi
	fi
#trojan_udp
	if [ $trojan_udp = 1 ];then
		t=`ps -w | grep ipt2socks |grep -v grep | wc -l`
		if [ $t = 0 ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") ipt2socks2 Error. Restart!" >> /tmp/ssrplus.log
			killall -q -9 ipt2socks
			ipt2socks -U -b 0.0.0.0 -4 -s 127.0.0.1 -p $ip_port -l $trojan_udp_port >/dev/null 2>&1 &
		fi
	fi
done
