#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@k3screenctrl[-1]
	add ucitrack k3screenctrl
	set ucitrack.@k3screenctrl[-1].init=k3screenctrl
	commit ucitrack
EOF
killall -HUP rpcd 2>/dev/null
exit 0
