#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=USB Printer Share via T$(TOPDIR)/feeds/packages
LUCI_DEPENDS:=+p910nd +kmod-usb-printer
PKG_VERSION:=1.0
PKG_RELEASE:=2

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
#applicatio$(TOPDIR)/feeds/packagesci-app-usb-printer/
#applicatio$(TOPDIR)/feeds/packagesci-app-usb-printer/
