#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@jd-dailybonus[-1]
	add ucitrack jd-dailybonus
	set ucitrack.@jd-dailybonus[-1].init=jd-dailybonus
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
