include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=cpulimit
PKG_VERSION:=cabeb9947c
PKG_RELEASE:=1
PKG_REV:=cabeb9947ccddd9a6e6ba14503e2a33063ac1b21

#PKG_SOURCE_PROTO:=git
#PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.bz2
#PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
#PKG_SOURCE_URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagessengi$(TOPDIR)/feeds/packagesulimit.git
#PKG_SOURCE_VERSION:=$(PKG_REV)

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesulimit
  CATEGORY:=Utilities
  TITLE:=cpulimit
  URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagessengi$(TOPDIR)/feeds/packagesulimit.git
endef

define Bui$(TOPDIR)/feeds/packagesepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP)$(TOPDIR)/feeds/packagesc/* $(PKG_BUILD_DIR)/
endef

define Packa$(TOPDIR)/feeds/packagesulim$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DI$(TOPDIR)/feeds/packagesulimit $($(TOPDIR)/feeds/packagesr/bin
endef


$(eval $(call BuildPackage,cpulimit))
