# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=Network Shares - CIFSD CI$(TOPDIR)/feeds/packagesB kernel fileserver
LUCI_DEPENDS:=+ksmbd-server
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-cifsd
PKG_VERSION:=1
PKG_RELEASE:=12

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
