include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=luci-app-openclash
PKG_VERSION:=0.42.03
PKG_RELEASE:=beta
PKG_MAINTAINER:=vernesong <http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesrneso$(TOPDIR)/feeds/packagesenClash>

PKG_BUILD_DIR:=$(BUILD_DI$(TOPDIR)/feeds/packagesPKG_NAME)

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesnfig
	select PACKAGE_libcap-bin
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAME)
	CATEGORY:=LuCI
	SUBMENU:=3. Applications
	TITLE:=LuCI support for clash
	PKGARCH:=all
	DEPENDS:=+iptables +dnsmasq-full +coreutils +coreutils-nohup +bash +curl +jsonfilter +ca-bundle +ipset +ip-full +iptables-mod-tproxy +iptables-mod-extra +libcap +libcap-bin +ruby +ruby-yaml
	MAINTAINER:=vernesong
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesscription
    A LuCI support for clash
endef

define Bui$(TOPDIR)/feeds/packagesepare
	$(CP) $(CURDI$(TOPDIR)/feeds/packagesot $(PKG_BUILD_DIR)
	$(CP) $(CURDI$(TOPDIR)/feeds/packagesasrc $(PKG_BUILD_DIR)
	$(foreach po,$(wildcard ${CURDI$(TOPDIR)/feeds/packages/zh-$(TOPDIR)/feeds/packagespo), \
		po2lmo $(po) $(PKG_BUILD_DI$(TOPDIR)/feeds/packagespatsubst %.po,%.lmo,$(notdir $(po)));)
	chmod 0755 $(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/init$(TOPDIR)/feeds/packagesenclash
	chmod -R 0755 $(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesenclash/
	mkdir -p $(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesnfig
	mkdir -p $(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesle_provider
	mkdir -p $(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesckup
	mkdir -p $(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesre
	mkdir -p $(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesencla$(TOPDIR)/feeds/packagesckup
	cp -f "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/conf$(TOPDIR)/feeds/packagesenclash" "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesencla$(TOPDIR)/feeds/packagesck$(TOPDIR)/feeds/packagesenclash"$(TOPDIR)/feeds/packagesv/null 2>&1
	cp -f "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesst$(TOPDIR)/feeds/packagesenclash_custom_rules.list" "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesencla$(TOPDIR)/feeds/packagesck$(TOPDIR)/feeds/packagesenclash_custom_rules.list"$(TOPDIR)/feeds/packagesv/null 2>&1
	cp -f "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesst$(TOPDIR)/feeds/packagesenclash_custom_rules_2.list" "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesencla$(TOPDIR)/feeds/packagesck$(TOPDIR)/feeds/packagesenclash_custom_rules_2.list"$(TOPDIR)/feeds/packagesv/null 2>&1
	cp -f "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesst$(TOPDIR)/feeds/packagesenclash_custom_hosts.list" "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesencla$(TOPDIR)/feeds/packagesck$(TOPDIR)/feeds/packagesenclash_custom_hosts.list"$(TOPDIR)/feeds/packagesv/null 2>&1
	cp -f "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesst$(TOPDIR)/feeds/packagesenclash_custom_fake_filter.list" "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesencla$(TOPDIR)/feeds/packagesck$(TOPDIR)/feeds/packagesenclash_custom_fake_filter.list"$(TOPDIR)/feeds/packagesv/null 2>&1
	cp -f "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesc/opencla$(TOPDIR)/feeds/packagesst$(TOPDIR)/feeds/packagesenclash_custom_domain_dns.list" "$(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesencla$(TOPDIR)/feeds/packagesck$(TOPDIR)/feeds/packagesenclash_custom_domain_dns.list"$(TOPDIR)/feeds/packagesv/null 2>&1
endef

define Bui$(TOPDIR)/feeds/packagesnfigure
endef

define Bui$(TOPDIR)/feeds/packagesmpile
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesnffiles
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packageseinst
$(TOPDIR)/feeds/packagesn/sh
if [ -f$(TOPDIR)/feeds/packagesc/conf$(TOPDIR)/feeds/packagesenclash" ]; then
	cp -f$(TOPDIR)/feeds/packagesc/conf$(TOPDIR)/feeds/packagesenclash"$(TOPDIR)/feeds/packagesp/openclash.bak"$(TOPDIR)/feeds/packagesv/null 2>&1
	cp -rf$(TOPDIR)/feeds/packagesc/openclash"$(TOPDIR)/feeds/packagesp/openclash"$(TOPDIR)/feeds/packagesv/null 2>&1
fi
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesstinst
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packageserm
$(TOPDIR)/feeds/packagesn/sh
	uci -q set openclash.config.enable=0
	uci -q commit openclash
	cp -f$(TOPDIR)/feeds/packagesc/conf$(TOPDIR)/feeds/packagesenclash"$(TOPDIR)/feeds/packagesp/openclash.bak"$(TOPDIR)/feeds/packagesv/null 2>&1
	cp -rf$(TOPDIR)/feeds/packagesc/openclash"$(TOPDIR)/feeds/packagesp/openclash"$(TOPDIR)/feeds/packagesv/null 2>&1
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesstrm
$(TOPDIR)/feeds/packagesn/sh
	rm -r$(TOPDIR)/feeds/packagesc/openclash
	rm -r$(TOPDIR)/feeds/packagesp/openclash.log
	rm -r$(TOPDIR)/feeds/packagesp/openclash_start.log
	rm -r$(TOPDIR)/feeds/packagesp/openclash_last_version
	rm -r$(TOPDIR)/feeds/packagesp/Proxy_Group
	rm -r$(TOPDIR)/feeds/packagesp/rules_name
	rm -r$(TOPDIR)/feeds/packagesp/rule_providers_name
	rm -r$(TOPDIR)/feeds/packagesp/clash_last_version
	rm -r$(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesencla$(TOPDIR)/feeds/packagesckup
	rm -r$(TOPDIR)/feeds/packagesp/openclash_fake_filter.list
	rm -r$(TOPDIR)/feeds/packagesp/openclash_servers_fake_filter.conf
	uci -q delete firewall.openclash
	uci -q commit firewall
	uci -q delete ucitrack.@openclash[-1]
	uci -q commit ucitrack
	rm -r$(TOPDIR)/feeds/packagesp/luci-*
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages8n
	$(INSTALL_DATA) $(PKG_BUILD_DI$(TOPDIR)/feeds/packages*.lmo $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages8n/
	$(CP) $(PKG_BUILD_DI$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packages$(1)/
	$(CP) $(PKG_BUILD_DI$(TOPDIR)/feeds/packagesas$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/luci/
endef

$(eval $(call BuildPackage,$(PKG_NAME)))
