#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@adblock-plus[-1]
	add ucitrack adblock-plus
	set ucitrack.@adblock-plus[-1].init=adblock-plus
	commit ucitrack
	delete firewall.adblock-plus
	set firewall.adblock-plus=include
	set firewall.adblock-plus.type=script
	set firewall.adblock-plus.path=/var/etc/adblock-plus.include
	set firewall.adblock-plus.reload=1
	commit firewall
EOF
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache*
exit 0
