#
# Copyright (C) 2021 ImmortalWrt
# <http$(TOPDIR)/feeds/packagesmmortalwrt.org>
#
# This is free software, licensed under the GNU General Public License v3.
# Se$(TOPDIR)/feeds/packagesCENSE for more information.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=pandownload-fake-server
PKG_VERSION:=1
PKG_RELEASE:=2

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesndownload-fake-server
  SECTION:=net
  CATEGORY:=Network
  SUBMENU:=Download Manager
  TITLE:=pandownload-fake-server
  PKGARCH:=all
endef

define Packa$(TOPDIR)/feeds/packagesndownload-fake-serv$(TOPDIR)/feeds/packagesscription
  Fake server for Pandownload.
endef

define Bui$(TOPDIR)/feeds/packagesmpile
	true
endef

define Packa$(TOPDIR)/feeds/packagesndownload-fake-serv$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesw
	$(CP)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesw/
endef

$(eval $(call BuildPackage,pandownload-fake-server))
