#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@verysync[-1]
	add ucitrack verysync
	service verysync enable
	set ucitrack.@verysync[-1].init=verysync
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
