#
# Copyright (C) 2021 ImmortalWrt
# <http$(TOPDIR)/feeds/packagesmmortalwrt.org>
#
# This is free software, licensed under the GNU General Public License v3.
# Se$(TOPDIR)/feeds/packagesCENSE for more information.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=microsocks
PKG_VERSION=1.0.2
PKG_RELEASE:=2

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=http$(TOPDIR)/feeds/packagesodeload.github.c$(TOPDIR)/feeds/packagesfl$(TOPDIR)/feeds/packagescrosoc$(TOPDIR)/feeds/packagesr.$(TOPDIR)/feeds/packages(PKG_VERSION)?
PKG_HASH:=skip

PKG_LICENSE:=MIT
PKG_LICENSE_FILES:=COPYING
PKG_MAINTAINER:=lean

PKG_BUILD_PARALLEL:=1
PKG_INSTALL:=1

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagescrosocks
	SECTION:=net
	CATEGORY:=Network
	SUBMENU:=Web Serve$(TOPDIR)/feeds/packagesoxies
	TITLE:=tiny, portable SOCKS5 server with very moderate resource usage
	URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesfl$(TOPDIR)/feeds/packagescrosocks
	DEPENDS:=+libpthread
endef

define Packa$(TOPDIR)/feeds/packagescrosoc$(TOPDIR)/feeds/packagesscription
	A SOCKS5 service that you can run on your remote boxes to tunnel connections
	through them, if for some reason SSH doesn't cut it for you.
endef

define Packa$(TOPDIR)/feeds/packagescrosoc$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/bin
	$(INSTALL_BIN) $(PKG_INSTALL_DI$(TOPDIR)/feeds/packagesr/loc$(TOPDIR)/feeds/packagesn/microsocks $($(TOPDIR)/feeds/packagesr/b$(TOPDIR)/feeds/packagescrosocks
endef

$(eval $(call BuildPackage,microsocks))
