#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autoreboot[-1]
	add ucitrack autoreboot
	service autoreboot enable
	set ucitrack.@autoreboot[-1].init=autoreboot
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
