#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@baidupcs-web[-1]
	add ucitrack baidupcs-web
	set ucitrack.@baidupcs-web[-1].init=baidupcs-web
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
