#
# Copyright (C) 2006-2011 Xmlad.com
#
# This is free software, licensed under the GNU General Public License v2.
# Se$(TOPDIR)/feeds/packagesCENSE for more information.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=wrtbwmon
PKG_VERSION:=1.2.1
PKG_RELEASE:=3

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagestbwmon
	SECTION:=net
	CATEGORY:=Network
	DEPENDS:=+iptables +@BUSYBOX_CONFIG_IP
	TITLE:=A Traffic Usage Monitor
	SUBMENU:=Tools
	PKGARCH:=all
endef

define Packa$(TOPDIR)/feeds/packagestbwm$(TOPDIR)/feeds/packagesscription
An CERNET client daemon,
Most usually used in China collages.
endef

define Bui$(TOPDIR)/feeds/packagesepare
endef

define Bui$(TOPDIR)/feeds/packagesnfigure
endef

define Bui$(TOPDIR)/feeds/packagesmpile
endef

define Packa$(TOPDIR)/feeds/packagestbwm$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/sbin $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagestbwmon
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagest/u$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesr/sbin/
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagest/u$(TOPDIR)/feeds/packagesa$(TOPDIR)/feeds/packagestbwm$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagestbwmon/

	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesc/config $($(TOPDIR)/feeds/packagesc/init.d $($(TOPDIR)/feeds/packagesc/hotplug$(TOPDIR)/feeds/packagesace
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagest/e$(TOPDIR)/feeds/packagesit$(TOPDIR)/feeds/packagestbwmon $($(TOPDIR)/feeds/packagesc/init$(TOPDIR)/feeds/packagestbwmon
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagest/e$(TOPDIR)/feeds/packagesnf$(TOPDIR)/feeds/packagestbwmon $($(TOPDIR)/feeds/packagesc/conf$(TOPDIR)/feeds/packagestbwmon
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagest/e$(TOPDIR)/feeds/packagestplug$(TOPDIR)/feeds/packagesa$(TOPDIR)/feeds/packages-wrtbwmon $($(TOPDIR)/feeds/packagesc/hotplug$(TOPDIR)/feeds/packagesa$(TOPDIR)/feeds/packages-wrtbwmon
endef

$(eval $(call BuildPackage,wrtbwmon))
