include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_LICENSE:=GPLv2
PKG_MAINTAINER:=Hua Shao <nossiac@163.com>

LUCI_TITLE:=LuCI support for mt wifi driver
LUCI_DEPENDS:=@TARGET_ramips +mt_wifi @!PACKAGE_kmod-mt7615d_dbdc
LUCI_PKGARCH:=all
PKG_VERSION:=1
PKG_RELEASE:=16

define Packa$(TOPDIR)/feeds/packagesci-app-mtwi$(TOPDIR)/feeds/packagesnffiles
/e$(TOPDIR)/feeds/packagesrele$(TOPDIR)/feeds/packages7615/
endef

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
