#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autoipsetadder[-1]
	add ucitrack autoipsetadder
	service autoipsetadder enable
	set ucitrack.@autoipsetadder[-1].init=autoipsetadder
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
