# Copyright (C) 2018-2019 Lienol
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI support for V2ray Server
LUCI_DEPENDS:=+xray-core
LUCI_PKGARCH:=all
PKG_VERSION:=1.1
PKG_RELEASE:=5

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
