include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI Support for homebridge
LUCI_DEPENDS:=+node

PKG_VERSION:=0.2.0
PKG_RELEASE:=1
PKG_DATE:=20201026
PKG_MAINTAINER:=lanxin Shang <shanglanxin@gmail.com>
PKG_LICENSE:=GPL-3.0-or-later

define Packa$(TOPDIR)/feeds/packagesci-app-homebrid$(TOPDIR)/feeds/packagesstinst
$(TOPDIR)/feeds/packagesn/sh
mkdir $${IPKG_INSTROO$(TOPDIR)/feeds/packagesc/homebrid$(TOPDIR)/feeds/packages/d$(TOPDIR)/feeds/packagesll 2>&1
exit 0
endef

define Packa$(TOPDIR)/feeds/packagesci-app-homebrid$(TOPDIR)/feeds/packagesnffiles
/e$(TOPDIR)/feeds/packagesnf$(TOPDIR)/feeds/packagesmebridge
endef

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
