#-- Copyright (C) 2018 hefeng <a520ass@hotmail.com>

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI support for PHTunnel
LUCI_DEPENDS:=+phtunnel +luci-lib-json
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=3

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature

