#PO = wifidog
#by walkingsky

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI wifidog config
LUCI_DEPENDS:=+wifidog
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-wifidog
PKG_VERSION:=2.0
PKG_RELEASE:=2

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
#
#
#
#

