#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@nps[-1]
	add ucitrack nps
	set ucitrack.@nps[-1].init=nps
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
