#
# Copyright (C) 2017 TDT AG <development@tdt.de>
#
# This is free software, licensed under the Apache License Version 2.0.
# See http$(TOPDIR)/feeds/packagesww.apache.o$(TOPDIR)/feeds/packagescens$(TOPDIR)/feeds/packagesCENSE-2.0 for more information.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=Support for Link Aggregation (Channel Bonding)
LUCI_DEPENDS:=+proto-bonding
LUCI_PKGARCH:=all

PKG_MAINTAINER:=Helge Mader <ma@dev.tdt.de>

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
