# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
# Maintained by eSir Playground <http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesirplaygrou$(TOPDIR)/feeds/packagesci-app-poweroff>

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=luci-app-poweroff
PKG_VERSION:=20200726
PKG_RELEASE:=1
LUCI_TITLE:=LuCI Support of PowerOff Router
LUCI_PKGARCH:=all

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
