#
# Copyright (C) 2019-2020 <wsdosh@gmail.com>
#
# This is free software, licensed under the Apache License, Version 3.0 .
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=luci-app-shortcutmenu
LUCI_TITLE:=LuCI Support for shortcutmenu
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=v0.0.5
PKG_LICENSE:=AGPL-3.0
PKG_MAINTAINER:=<http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesusha$(TOPDIR)/feeds/packagesci-app-shortcutmenu>

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
