
include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=SYSU H3C 802.1X Client for LuCI
LUCI_DEPENDS:=+sysuh3c
LUCI_DESCRIPTION:=This package contains LuCI configuration pages for SYSU H3C.
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=3
PKG_LICENSE:=GPL-3.0
PKG_LICENSE_FILES:=LICENSE

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
