# From http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesrkDean$(TOPDIR)/feeds/packagesci-app-filebrowser
# From http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesuarth$(TOPDIR)/feeds/packages-my-openw$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesst$(TOPDIR)/feeds/packagesua$(TOPDIR)/feeds/packagesci-app-fileassistant
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI support for Fileassistant
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=2

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature