include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=chinadns-ng
PKG_VERSION:=1.0-beta.24
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesinadns-ng.git
PKG_MIRROR_HASH:=4b0a159e1ecd81392a67b31528b0430afa991bfceef5dd60d2d843edfccb6b12
PKG_SOURCE_VERSION:=df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb

PKG_BUILD_PARALLEL:=1
PKG_USE_MIPS16:=0

PKG_LICENSE:=GPLv3
PKG_LICENSE_FILES:=LICENSE
PKG_MAINTAINER:=pexcn <i@pexcn.me>

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesinadns-ng
	SECTION:=net
	CATEGORY:=Network
	TITLE:=ChinaDNS next generation, refactoring with epoll and ipset
	URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesinadns-ng
	DEPENDS:=+ipset
endef

define Packa$(TOPDIR)/feeds/packagesinadns-$(TOPDIR)/feeds/packagesscription
ChinaDNS next generation, refactoring with epoll and ipset.
endef

define Packa$(TOPDIR)/feeds/packagesinadns-$(TOPDIR)/feeds/packagesnffiles
endef

define Packa$(TOPDIR)/feeds/packagesinadns-$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DI$(TOPDIR)/feeds/packagesinadns-ng $($(TOPDIR)/feeds/packagesr/bin
endef

$(eval $(call BuildPackage,chinadns-ng))
