# Copyright (C) 2019 CCnut
#
# This is free software, licensed under the GNU General Public License v2.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Netkeeper-Interception
LUCI_DEPENDS:=+luci-compat +netkeeper-interception +luci-proto-netkeeper
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
