# Copyright (C) 2019 CCnut
#
# This is free software, licensed under the GNU General Public License v2.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI Support for Netkeeper-Interception
LUCI_DEPENDS:=+luci-compat +netkeeper-interception +luci-proto-netkeeper
LUCI_PKGARCH:=all
PKG_VERSION:=0.1
PKG_RELEASE:=1

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
