# Copyright (C) 2018-2020 Lienol <lawlienol@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI support for PPPoE Relay
LUCI_DEPENDS:=+rp-pppoe-common +rp-pppoe-relay
LUCI_PKGARCH:=all
PKG_VERSION:=1
PKG_RELEASE:=2-20200326

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
