include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=Default Settings
LUCI_DEPENDS:=+luci-base +@LUCI_LANG_zh_Hans
PKG_MAINTAINER:=
PKG_LICENSE:=GPL-3.0-or-later

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature



