include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI Support for advanced and filebrowser
LUCI_DEPENDS:=
PKG_MAINTAINER:=sirpdboy
PKG_LICENSE:=GPL-3.0-or-later

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
