####
 #  File$(TOPDIR)/feeds/packageskefile
 #  Project: rclone-webui-react
 #  File Created: Thursday, 10th October 2019 5:57:39 pm
 #  Author: ElonH[EH](elonhhuang@gmail.com)
 #  License: GNU General Public License v3.0 or later(htt$(TOPDIR)/feeds/packagesww.gnu.o$(TOPDIR)/feeds/packagescens$(TOPDIR)/feeds/packagesl-3.0-standalone.html)
 #	Copyright (C) 2019 [ElonH]
####

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=rclone-webui-react
PKG_VERSION:=0.1.0
PKG_RELEASE:=1


PKG_LICENSE:=GPLv3
PKG_MAINTAINER:=ElonH <elonhhuang@gmail.com>

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

PKG_SOURCE:=currentbuild.zip
PKG_SOURCE_URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packageslo$(TOPDIR)/feeds/packageslone-webui-rea$(TOPDIR)/feeds/packagesleas$(TOPDIR)/feeds/packageswnlo$(TOPDIR)/feeds/packages(PKG_VERSION)/
PKG_BUILD_DIR:=$(BUILD_DI$(TOPDIR)/feeds/packagesPKG_NAME)-$(PKG_VERSION)
PKG_HASH:=skip

define Packa$(TOPDIR)/feeds/packagesPKG_NAME)
	SECTION:=net
	CATEGORY:=Network
	SUBMENU:=File Transfer
	SUBMENU:=Cloud Manager
	TITLE:=A reactjs based web UI for rclone
	URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packageslo$(TOPDIR)/feeds/packageslone-webui-react
	PKGARCH:=all
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesscription
	A full fledged UI for the rclone cloud sync tool.
endef

define Bui$(TOPDIR)/feeds/packagesepare
	mkdir -vp $(PKG_BUILD_DIR)
	unzip -od $(PKG_BUILD_DIR) $(DL_DI$(TOPDIR)/feeds/packagesPKG_SOURCE)
endef

define Bui$(TOPDIR)/feeds/packagesnfigure
endef

define Bui$(TOPDIR)/feeds/packagesmpile
	echo "$(PKG_NAME) Compile Skiped!"
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesw/rclone-webui-react
	$(CP) $(PKG_BUILD_DI$(TOPDIR)/feeds/packagesi$(TOPDIR)/feeds/packages$($(TOPDIR)/feeds/packagesw/rclone-webui-react
endef

$(eval $(call BuildPackage,$(PKG_NAME)))
