#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@https-dns-proxy[-1]
	add ucitrack https-dns-proxy
	set ucitrack.@https-dns-proxy[-1].init=https-dns-proxy
	commit ucitrack
EOF
rm -rf /var/luci-modulecache/; rm -f /var/luci-indexcache;
exit 0
