#
# Copyright (C) 2015-2016 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=k3wifi
PKG_VERSION:=1
PKG_RELEASE:=2

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesPKG_NAME)
	TITLE:=k3wifi
	DEPENDS:=
	URL:=htt$(TOPDIR)/feeds/packagesww.k3wifi.com/
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesscription
  k3wifi fw
endef

define Bui$(TOPDIR)/feeds/packagesepare
endef

define Bui$(TOPDIR)/feeds/packagesnfigure
endef

define Bui$(TOPDIR)/feeds/packagesmpile
endef


define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesb
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesb/firmware
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesb/firmwa$(TOPDIR)/feeds/packagescm
	$(INSTALL_DATA)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagesb/firmwa$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagescmfmac4366c-pcie.bin $($(TOPDIR)/feeds/packagesb/firmwa$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagescmfmac4366c-pcie.bin
endef

$(eval $(call BuildPackage,$(PKG_NAME)))
