# Copyright (C) 2018-2020 Lienol <lawlienol@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI support for PPPoE Server
LUCI_DEPENDS:=+rp-pppoe-common +rp-pppoe-server
LUCI_PKGARCH:=all
PKG_VERSION:=1
PKG_RELEASE:=8-20200326

define Packa$(TOPDIR)/feeds/packagesci-app-pppoe-serv$(TOPDIR)/feeds/packageseinst
$(TOPDIR)/feeds/packagesn/sh
rm -rf $${IPKG_INSTROO$(TOPDIR)/feeds/packagesc/conf$(TOPDIR)/feeds/packagespoe-server$(TOPDIR)/feeds/packagesv/null 2>&1
rm -rf $${IPKG_INSTROO$(TOPDIR)/feeds/packagesc/init$(TOPDIR)/feeds/packagespoe-server$(TOPDIR)/feeds/packagesv/null 2>&1
exit 0
endef

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature