include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=sysuh3c
PKG_VERSION:=1.0
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesswellir$(TOPDIR)/feeds/packagesc.git
PKG_MIRROR_HASH:=3175d4c9d6a4b39a5e4b2ef347e938c092305854057196961f70935723532170
PKG_SOURCE_VERSION:=fdf66c3

PKG_LICENSE:=GPL-3.0
PKG_LICENSE_FILES:=LICENSE

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesPKG_NAME)
	SECTION:=net
	CATEGORY:=Network
	TITLE:=H3C client
	SUBMENU:=Campus Network
endef

define Bui$(TOPDIR)/feeds/packagesnfigure
	$(call Bui$(TOPDIR)/feeds/packagesnfigu$(TOPDIR)/feeds/packagesfault)
endef

define Packa$(TOPDIR)/feeds/packagesPKG_NAM$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/sbin
	$(INSTALL_BIN) $(PKG_BUILD_DI$(TOPDIR)/feeds/packagesc $($(TOPDIR)/feeds/packagesr/sb$(TOPDIR)/feeds/packagessuh3c
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesc/config
	$(INSTALL_CONF)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagessuh3c.config $($(TOPDIR)/feeds/packagesc/conf$(TOPDIR)/feeds/packagessuh3c
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesc/init.d
	$(INSTALL_BIN)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packagessuh3c.init $($(TOPDIR)/feeds/packagesc/init$(TOPDIR)/feeds/packagessuh3c
endef

$(eval $(call BuildPackage,$(PKG_NAME)))
