#!/bin/sh
touch /etc/config/arpbind

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@arpbind[-1]
	add ucitrack arpbind
	set ucitrack.@arpbind[-1].init=arpbind
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
