#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mwan3helper[-1]
	add ucitrack mwan3helper
	set ucitrack.@mwan3helper[-1].init=mwan3helper
	commit ucitrack
EOF

rm -f /tmp/luci*
killall -HUP rpcd 2>/dev/null
exit 0
