#
# Copyright (C) 2009 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# Se$(TOPDIR)/feeds/packagesCENSE for more information.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=luci-lib-fs
PKG_VERSION:=1.0
PKG_RELEASE:=2

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesci-lib-fs
  SECTION:=lang
  CATEGORY:=Languages
  SUBMENU:=Lua
  TITLE:=luci-lib-fs
  URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesthoms$(TOPDIR)/feeds/packagesenwrt-luci
  DEPENDS:=+luci +luci-lib-nixio
  PKGARCH:=all
endef

define Bui$(TOPDIR)/feeds/packagesmpile
	true
endef

define Packa$(TOPDIR)/feeds/packagesci-lib-$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/luci
	$(CP)$(TOPDIR)/feeds/packagesl$(TOPDIR)/feeds/packages.lua $($(TOPDIR)/feeds/packagesr/l$(TOPDIR)/feeds/packagesa/lu$(TOPDIR)/feeds/packages.lua
endef

$(eval $(call BuildPackage,luci-lib-fs))
