#
# Copyright (C) 2021 ImmortalWrt
#
# This is free software, licensed under the GNU General Public License v2.
# Se$(TOPDIR)/feeds/packagesCENSE for more information.
#

include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=bpytop
PKG_VERSION:=1.0.62
PKG_RELEASE:=$(AUTORELEASE)

PYPI_NAME:=bpytop
PKG_HASH:=skip

PKG_LICENSE:=Apache-2.0
PKG_LICENSE_FILES:=LICENSE

include $(TOPDIR)/feeds/packages/la$(TOPDIR)/feeds/packagesth$(TOPDIR)/feeds/packagespi.mk
include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk
include $(TOPDIR)/feeds/packages/la$(TOPDIR)/feeds/packagesth$(TOPDIR)/feeds/packagesthon3-package.mk

define Packa$(TOPDIR)/feeds/packagesytop
  SECTION:=admin
  CATEGORY:=Administration
  TITLE:=Python port of bashtop
  URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagesistocrat$(TOPDIR)/feeds/packagesytop
  DEPENDS:=+python3-psutil +python3-setuptools
endef

define Packa$(TOPDIR)/feeds/packagesyt$(TOPDIR)/feeds/packagesscription
  Resource monitor that shows usage and stats for
  processor, memory, disks, network and processes.
endef

define Packa$(TOPDIR)/feeds/packagesyt$(TOPDIR)/feeds/packagesstall
	$(call Py3Packa$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesstall,$(PKG_INSTALL_DIR))
	$(INSTALL_DIR) $(1)
	$(CP) $(PKG_INSTALL_DI$(TOPDIR)/feeds/packages$(1)/
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/share
	$(CP) $(PKG_BUILD_DI$(TOPDIR)/feeds/packagesytop-themes $($(TOPDIR)/feeds/packagesr/sha$(TOPDIR)/feeds/packagesytop
endef

$(eval $(call Py3Package,bpytop))
$(eval $(call BuildPackage,bpytop))
#$(eval $(call BuildPackage,bpytop-src))
