#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ngrokc[-1]
	add ucitrack ngrokc
	service ngrokc enable
	set ucitrack.@ngrokc[-1].init=ngrokc
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
