#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ngrokc[-1]
	add ucitrack ngrokc
	set ucitrack.@ngrokc[-1].init=ngrokc
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
