#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@softethervpn5[-1]
	add ucitrack softethervpn5
	set ucitrack.@softethervpn5[-1].init=softethervpn5
	commit ucitrack
EOF

/etc/init.d/softethervpn5 stop

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
