#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@softethervpn5[-1]
	add ucitrack softethervpn5
	service softethervpn5 enable
	set ucitrack.@softethervpn5[-1].init=softethervpn5
	commit ucitrack
EOF

/etc/init.d/softethervpn5 stop

rm -f /tmp/luci-indexcache
exit 0
