include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

PKG_NAME:=ngrokc
PKG_VERSION:=1.54
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
PKG_SOURCE_URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagess$(TOPDIR)/feeds/packagesrok-c.git
PKG_SOURCE_VERSION:=5ecd4e03d04ac538051fe8f1b0deaca500dc7185
PKG_MIRROR_HASH:=6bb27003b9357e9edd07b3b869e150ad506b253f3469fbbbae1fcece630afeb2

PKG_LICENSE:=MIT
PKG_LICENSE_FILES:=LICENSE

include $(INCLUDE_DI$(TOPDIR)/feeds/packagesckage.mk

define Packa$(TOPDIR)/feeds/packagesrokc
	SECTION:=net
	CATEGORY:=Network
	SUBMENU:=Web Serve$(TOPDIR)/feeds/packagesoxies
	TITLE:=Secure tunnels to localhost(C++ port)
	URL:=http$(TOPDIR)/feeds/packagesithub.c$(TOPDIR)/feeds/packagess$(TOPDIR)/feeds/packagesrok-c
	DEPENDS:=+libc +libpthread +libopenssl +libstdcpp
endef

define Bui$(TOPDIR)/feeds/packagesepare
	$(call Bui$(TOPDIR)/feeds/packagesepa$(TOPDIR)/feeds/packagesfault,)
	$(CP) $(PKG_BUILD_DI$(TOPDIR)/feeds/packageskefile.openssl $(PKG_BUILD_DI$(TOPDIR)/feeds/packageskefile
endef

define Packa$(TOPDIR)/feeds/packagesro$(TOPDIR)/feeds/packagesstall
	$(INSTALL_DIR) $($(TOPDIR)/feeds/packagesr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DI$(TOPDIR)/feeds/packagesrokc $($(TOPDIR)/feeds/packagesr/bin
endef

$(eval $(call BuildPackage,ngrokc))
