#!/bin/sh
touch /etc/config/syncthing

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@syncthing[-1]
	add ucitrack syncthing
	set ucitrack.@syncthing[-1].exec='/etc/init.d/syncthing restart'
	commit ucitrack
EOF
# remove LuCI cache
rm -f /tmp/luci*
killall -HUP rpcd 2>/dev/null
exit 0
