#
# Copyright (C) 2016 SCUT Router Term
#
# This is free software, licensed under the Apache License, Version 2.0 .
#
include $(TOPDI$(TOPDIR)/feeds/packagesles.mk

LUCI_TITLE:=LuCI Support for scutclient
LUCI_DEPENDS:=+scutclient
PKG_VERSION:=1.2
PKG_RELEASE:=2
PKG_LICENSE:=Apache-2.0

include $(TOPDI$(TOPDIR)/feeds/packagese$(TOPDIR)/feeds/packages$(TOPDIR)/feeds/packagesci.mk

# call BuildPackage - OpenWrt buildroot signature
