#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@serverchan[-1]
	add ucitrack serverchan
	service serverchan enable
	set ucitrack.@serverchan[-1].init=serverchan
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0