#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@serverchan[-1]
	add ucitrack serverchan
	set ucitrack.@serverchan[-1].init=serverchan
	commit ucitrack
EOF

rm -rf /tmp/luci-*
killall -HUP rpcd 2>/dev/null
exit 0