#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@serverchand[-1]
	add ucitrack serverchand
	set ucitrack.@serverchand[-1].init=serverchand
	commit ucitrack
EOF

rm -rf /tmp/luci-*
killall -HUP rpcd 2>/dev/null
exit 0
