#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qbittorrent[-1]
	add ucitrack qbittorrent
	set ucitrack.@qbittorrent[-1].init=qbittorrent
	commit ucitrack
EOF

/etc/init.d/qbittorrent stop
rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
