#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frp[-1]
	add ucitrack frp
	set ucitrack.@frp[-1].init=frp
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
