#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mwol[-1]
	add ucitrack mwol
	set ucitrack.@mwol[-1].init=mwol
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
