include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for babeld
LUCI_DEPENDS:=+babeld +luci-compat
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/packages/luci.mk

# call BuildPackage - OpenWrt buildroot signature
